version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y git
      - run:
          name: Deploy to GitHub Pages
          command: |
            git config --global user.email "harishvijayakumar027@gmail.com"
            git config --global user.name "harishvijayakumar27"
            # Ensure we have the latest main branch
            git checkout main
            git pull origin main
            # Copy the contents to the GitHub Pages directory
            cp -r ./simple-webpage/* ./  # This assumes your HTML files are in simple-webpage/
            # Add, commit, and push changes
            git add .
            git commit -m "Deploy to GitHub Pages"
            git push origin main

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build

